dash_port: 7003
data_main_path: data
db_connection:
  data_source: postgresql
  db: customeranalytics # abtestdb
  is_from_db: true
  password: 1234
  port: 5440
  server: 127.0.0.1
  user: mac
docker: /
docs_main_path: docs
is_from_db: false
log_main_path: logs
model_main_path: models
output_file_name: results
port_ranges: 6000*7000
prediction_date: 2020-03-01
server: /tmp/mnt
train_end_date: 2020-01-01
web_port: 7002

